eureka:
  client:
    service-url:
      defaultZone: http://localhost:8760/eureka/
server:
  port: 8761
spring:
  application:
    name: eureka-client-one
logging:
  file: "logs/eureka-client-one.log"
management:
  security:
    enabled: false

